version: '3.9'

services:
  #  MYSQL
  sports-field-booking-mysql:
    image: mysql:latest
    container_name: sports-field-booking-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: sports_field_booking_db
      MYSQL_USER: group23
      MYSQL_PASSWORD: gRoUp23IsThEbEsT#
    volumes:
      - ./docker/sports-field-booking-mysql-init-db:/docker-entrypoint-initdb.d:ro
      - sports-field-booking-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  # PHPMYADMIN
  sports-field-booking-phpmyadmin:
    image: phpmyadmin:latest
    container_name: sports-field-booking-phpmyadmin
    depends_on:
      [ sports-field-booking-mysql ]
    environment:
      PMA_HOST: sports-field-booking-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8000:80"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  #  REDIS
  sports-field-booking-redis:
    image: redis:latest
    container_name: sports-field-booking-redis
    ports:
      - "6379:6379"
    volumes:
      - sports-field-booking-redis-data:/data
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  #  REDIS INSIGHT
  sports-field-booking-redis-insight:
    image: redis/redisinsight:latest
    container_name: sports-field-booking-redis-insight
    volumes:
      - sports-field-booking-redis-insight-data:/db
    ports:
      - "5540:5540"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  # KAFKA BROKER
  sports-field-booking-kafka-broker:
    image: bitnami/kafka:3.5.2-debian-12-r24
    container_name: sports-field-booking-kafka-broker
    hostname: sports-field-booking-kafka-broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_KRAFT_MODE: true
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT_LOCAL://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_LOCAL://localhost:9092,PLAINTEXT_DOCKER://sports-field-booking-kafka-broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_LOCAL:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@sports-field-booking-kafka-broker:9094
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
      - sports-field-booking-kafka-broker-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  # KAFKA UI
  sports-field-booking-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: sports-field-booking-kafka-ui
    depends_on:
      [ sports-field-booking-kafka-broker ]
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://sports-field-booking-kafka-broker:9093
    volumes:
      - sports-field-booking-kafka-ui-data:/app/kafka-ui/data
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  # MINIO
  sports-field-booking-minio:
    image: minio/minio:RELEASE.2024-08-26T15-33-07Z.fips
    container_name: sports-field-booking-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - sports-field-booking-minio-data:/data:r
    environment:
      MINIO_ROOT_USER: group23
      MINIO_ROOT_PASSWORD: gRoUp23IsThEbEsT#
    command: server /data --console-address ":9001"

  #_______________________________________GRAFANA STACK_______________________________________
  #  TEMPO
  sports-field-booking-tempo:
    image: grafana/tempo:main-bbe0435
    container_name: sports-field-booking-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/grafana-stack/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/grafana-stack/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100" # Tempo
      - "9411:9411" # zipkin
      - "4317:4317" # OTel
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  #  LOKI
  sports-field-booking-loki:
    image: grafana/loki:main
    container_name: sports-field-booking-loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  #  PROMETHEUS
  sports-field-booking-prometheus:
    image: prom/prometheus:main
    container_name: sports-field-booking-prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/grafana-stack/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  #  GRAFANA
  sports-field-booking-grafana:
    image: grafana/grafana:10.1.0
    container_name: sports-field-booking-grafana
    environment:
      #      GF_AUTH_ANONYMOUS_ENABLED: true
      #      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      #      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_SECURITY_ADMIN_USER: group23
      GF_SECURITY_ADMIN_PASSWORD: gRoUp23IsThEbEsT#
    volumes:
      #      - ./docker/grafana-stack/grafana:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana-stack/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./docker/grafana-stack/grafana/dashboards:/etc/grafana/provisioning/dashboards
    #      - ./docker/grafana-stack/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  #_______________________________________ELK STACK_______________________________________
  # ELASTICSEARCH
  sports-field-booking-elasticsearch:
    image: elasticsearch:8.15.0
    container_name: sports-field-booking-elasticsearch
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - sports-field-booking-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  # KIBANA
  sports-field-booking-kibana:
    image: kibana:8.15.0
    container_name: sports-field-booking-kibana
    depends_on:
      [ sports-field-booking-elasticsearch ]
    environment:
      ELASTICSEARCH_HOSTS: http://sports-field-booking-elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - sports-field-booking-network
    restart: unless-stopped

  # LOGSTASH
  sports-field-booking-logstash:
    image: logstash:8.15.0
    container_name: sports-field-booking-logstash
    depends_on:
      [ sports-field-booking-elasticsearch ]
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./docker/elk-stack/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./docker/elk-stack/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - sports-field-booking-network
    restart: unless-stopped


networks:
  sports-field-booking-network:
    driver: bridge

volumes:
  sports-field-booking-mysql-data:
  sports-field-booking-redis-data:
  sports-field-booking-redis-insight-data:
  sports-field-booking-kafka-broker-data:
  sports-field-booking-kafka-ui-data:
  sports-field-booking-minio-data:
  sports-field-booking-elasticsearch-data:
